### ISSUE TITLE
Seg fault for specific boundary selection

### ISSUE THREAD

**Issue by kpwebb** [conveyal/vanilla-extract#10]
Using the current planet.pbf db on osm.conveyal.com this command results in a seg fault:

vex /mnt/osm/db 13.923403897723343 120.9375 16.636191878397646 123.75 manila.pbf

Core was generated by `'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004053f5 in load_tags (coded_tags=0x7f566e6f5000 <error: Cannot access memory at address 0x7f566e6f5000>, keys=0x2271c2c8 <payload_buffer+864936>, 
    vals=0x2271c2d8 <payload_buffer+864952>) at pbf-write.c:244
244	static size_t load_tags(uint8_t *coded_tags, /*OUT*/ uint32_t **keys, /*OUT*/ uint32_t **vals) {

**Comment by heffergm** [comment]
I'm seeing something similar. I noticed it only because this sometimes results in zero-length output files:

vex /metro_extracts/work/vex_db "47.225" "8.275" "47.533" "8.800" zurich.pbf
Mapping file '/metro_extracts/work/vex_db/grid' of size 2.0 GiB.
Mapping file '/metro_extracts/work/vex_db/ways' of size 3.0 GiB.
Mapping file '/metro_extracts/work/vex_db/nodes' of size 44.7 GiB.
Mapping file '/metro_extracts/work/vex_db/node_refs' of size 29.8 GiB.
Mapping file '/metro_extracts/work/vex_db/way_blocks' of size 6.6 GiB.
Mapping file '/metro_extracts/work/vex_db/relations' of size 45.8 MiB.
Mapping file '/metro_extracts/work/vex_db/rel_members' of size 610.4 MiB.
min = (47.22500, 8.27500) max = (47.53300, 8.80000)
Acquiring shared read lock on database.
Opening file 'zurich.pbf' as append stream.
Mapping file '/metro_extracts/work/vex_db/tags' of size 4.0 GiB.
Mapping file '/metro_extracts/work/vex_db/tags.005' of size 4.0 GiB.
Mapping file '/metro_extracts/work/vex_db/tags.003' of size 4.0 GiB.
Mapping file '/metro_extracts/work/vex_db/tags.006' of size 4.0 GiB.
Mapping file '/metro_extracts/work/vex_db/tags.001' of size 4.0 GiB.
Mapping file '/metro_extracts/work/vex_db/tags.002' of size 4.0 GiB.
Mapping file '/metro_extracts/work/vex_db/tags.004' of size 4.0 GiB.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Segmentation fault (core dumped)

**Comment by abyrd** [comment]
There's a fixed-size table for tag references that might be at fault. Have either of you seen anything like:

```
too many key/val string table references in a block.
Segmentation fault (core dumped)
```

**Comment by heffergm** [comment]
I haven't seen that particular message prior to the segfault.

**Comment by abyrd** [comment]
I can't reproduce the manila or zurich segfault on Philippines/Switzerland extracts loaded into vex, seems to only happen on full planet. Investigating.

**Comment by abyrd** [comment]
@heffergm any chance you were loading a new planet file into an existing database directory? That has undefined behavior and I've seen it cause segfaults before. I should have mentioned that in the README. I have added a check and VEX will only load data into a new, empty directory now.

**Comment by heffergm** [comment]
It’s possible I had overwritten the db directory, but I’m not 100% sure. Didn’t realize that was a bad idea. I’ll modify the behavior for re-creating the data dir and when I get a chance to test let you know if it changes things.

--
Grant Heffernan

**Comment by abyrd** [comment]
Note that the new code attempts to create the data dir when you load a PBF, so all you need to do is remove the data directory before running the load action.

**Comment by heffergm** [comment]
Got it, thanks.

--
Grant Heffernan

**Comment by heffergm** [comment]
Getting the following trying to build the latest:

```
---- Begin output of make -j36 ----
STDOUT: clang  -Wall -std=gnu99 -O3 -g    -c -o dedup.o dedup.c
clang  -Wall -std=gnu99 -O3 -g    -c -o fileformat.pb-c.o fileformat.pb-c.c
clang  -Wall -std=gnu99 -O3 -g    -c -o idtracker.o idtracker.c
clang  -Wall -std=gnu99 -O3 -g    -c -o intpack.o intpack.c
clang  -Wall -std=gnu99 -O3 -g    -c -o map.o map.c
clang  -Wall -std=gnu99 -O3 -g    -c -o osmformat.pb-c.o osmformat.pb-c.c
clang  -Wall -std=gnu99 -O3 -g    -c -o pbf-read.o pbf-read.c
clang  -Wall -std=gnu99 -O3 -g    -c -o pbf-write.o pbf-write.c
clang  -Wall -std=gnu99 -O3 -g    -c -o tags.o tags.c
clang  -Wall -std=gnu99 -O3 -g    -c -o vex.o vex.c
STDERR: In file included from pbf-write.c:2:
In file included from ./pbf.h:4:
./fileformat.pb-c.h:7:10: fatal error: 'protobuf-c/protobuf-c.h' file not found
#include <protobuf-c/protobuf-c.h>
```

**Comment by abyrd** [comment]
Yeah there have apparently been some changes to the protobuf-c library. We should be generating those source files as part of the build process instead of checking them in. Do this:

```
$ rm fileformat.pb*
$ rm osmformat.pb*
$ protoc-c fileformat.proto --c_out=.
$ protoc-c osmformat.proto --c_out=.
$ make clean && make
```

**Comment by abyrd** [comment]
Oh and you need to install the package  protobuf-c-compiler (on debian or ubuntu).

**Comment by heffergm** [comment]
So testing on a fresh db, I'm seeing different but odd behavior:

```
vex /metro_extracts/work/vex_db 47.225 8.275 47.533 8.800 zurich.pbf
Mapping file '/metro_extracts/work/vex_db/grid' of size 2.0 GiB.
Could not memory map file.
```

But this is perfectly fine:

```
root@extractor1:/tmp# vex /mnt/metro/vex_db 51.481 -0.674 51.544 -0.514 slough_england.osm.pbf
Mapping file '/mnt/metro/vex_db/grid' of size 2.0 GiB.
Mapping file '/mnt/metro/vex_db/ways' of size 3.0 GiB.
Mapping file '/mnt/metro/vex_db/nodes' of size 44.7 GiB.
Mapping file '/mnt/metro/vex_db/node_refs' of size 29.8 GiB.
Mapping file '/mnt/metro/vex_db/way_blocks' of size 6.6 GiB.
Mapping file '/mnt/metro/vex_db/relations' of size 45.8 MiB.
Mapping file '/mnt/metro/vex_db/rel_members' of size 610.4 MiB.
min = (51.48100, -0.67400) max = (51.54400, -0.51400)
Acquiring shared read lock on database.
Opening file 'slough_england.osm.pbf' as append stream.
Mapping file '/mnt/metro/vex_db/tags' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.002' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.001' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.003' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.004' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.005' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.006' of size 4.0 GiB.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Writing data blob containing nodes.
Mapping file '/mnt/metro/vex_db/tags.008' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.007' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.015' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.010' of size 4.0 GiB.
Mapping file '/mnt/metro/vex_db/tags.009' of size 4.0 GiB.
Writing data blob containing ways.
Writing data blob containing relations.
```

**Comment by heffergm** [comment]
I'm consistently getting what I suspect are segfaults for these extracts, based on their 0 length size:

0	antwerp_belgium.osm.pbf
0	berlin_germany.osm.pbf
0	cheshire_england.osm.pbf
0	dakar_senegal.osm.pbf
0	dresden_germany.osm.pbf
0	dublin_ireland.osm.pbf
0	glasgow_scotland.osm.pbf
0	hamburg_germany.osm.pbf
0	hangzhou_china.osm.pbf
0	johannesburg_south-africa.osm.pbf
0	leipzig_germany.osm.pbf
0	manchester_england.osm.pbf
0	southampton_england.osm.pbf
0	winterthur_switzerland.osm.pbf


You can find the corresponding bbox's here: https://github.com/mapzen/metroextractor-cities/blob/master/cities.json

**Comment by heffergm** [comment]
Long story short:

- the original stack trace was likely me having overwritten an existing db with a new one, so I've implemented your suggestion and will purge the directory ahead of time

- the subsequent failures weren't vex, they were part of a downstream osmconvert process. Unfortunately we need to support .osm output, and it looks like osmconvert chokes on converting the vex pbf output

**Comment by abyrd** [comment]
OK @heffergm thanks for the feedback. Will take it into consideration in further work.

**Comment by abyrd** [comment]
After a clean import of planet.osm on our dev server it still segfaults. The reason however is probably very simple: the number of ways in OSM grew much faster than I expected and exceeded a constant I had defined.

**Comment by abyrd** [comment]
Confirmed, the continuing segfaults were due to some table size constants that were too small. I'm adding range checks so this doesn't fail silently in the future and increasing the sizes. In the long run though they will need to expand automatically to accommodate any possible entity index.
