### ISSUE TITLE
building GTFS graph from analyst-server crashes local vex server

### ISSUE THREAD

**Issue by knaaptime** [conveyal/vanilla-extract#5]
Not sure if i should post this issue here or with analyst-server...

I have working instances of vanilla-extract and analyst-server. Both are running on the same server and analyst-server is configured to call the vex server at 0.0.0.0:82

each time i try to create a scenario (build graph) the (nodejs) vex server crashes with the following error:

    vex server running at 0.0.0.0:8282

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: spawn ENOENT
        at errnoException (child_process.js:988:11)
        at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by knaaptime** [comment]
fixed the issue by changing VEX_CMD to './vex' instead of 'vex'

**Comment by mattwigway** [comment]
ah, should have documented that. yes, vex needs to be in the PATH for vexserver to work.
